name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Triggers when changes are pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Set up Google credentials from secret
      - name: Set up Google credentials
        run: echo "$CREDENTIALS" > credentials.json
        env:
          CREDENTIALS: ${{ secrets.CREDENTIALS }}

      # Step 4: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run the Streamlit app
      - name: Run Streamlit app
        run: |
          streamlit run your_script.py
